### ISSUE TITLE
Open Source Helps!

### ISSUE THREAD

**Issue by WeileiZeng** [nat236919/covid19-api#29]
Thanks for your work to help the people in need! Your site has been added! I currently maintain the Open-Source-COVID-19 page, which collects all open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

https://weileizeng.github.io/Open-Source-COVID-19/

Cheers!

**Comment by nat236919** [comment]
Thank you so much. Your project is certainly helpful.

**Comment by RamanujamVaradhan** [comment]
A big thanks to the creators of this API.
I have created a project the provides projections on the numbers based on the growth rate from the past 3 days.

https://covid19virusprojections.herokuapp.com/
