### ISSUE TITLE
Recovered endpoint returns always 0

### ISSUE THREAD

**Issue by spacecowb0y** [nat236919/covid19-api#296]
**Describe the bug**
There must be something wrong with the `/recovered` endpoint, it always returns 0.

**Comment by nat236919** [comment]
@spacecowb0y Thank you for raising this issue. I think it is because the source data (https://github.com/CSSEGISandData/COVID-19) discontinued providing **Recovered** and **Active** according to this issue https://github.com/CSSEGISandData/COVID-19/issues/4465

**Comment by nat236919** [comment]
Yeah, sorry about that. I think what we can do now is to ignore **Recovered** completely.

However, if **Active** is required, we can calculate roughly as 

`active = (confirmed - death) - *recovered`
*assume it will be zero
