### ISSUE TITLE
CR country code 

### ISSUE THREAD

**Issue by mcteapot** [nat236919/covid19-api#32]
When calling CR for Costa_Rica it returns 

"{"South_Africa":{"confirmed":62,"deaths":0,"recovered":0},"Costa_Rica":{"confirmed":41,"deaths":0,"recovered":0},"Central_African_Republic":{"confirmed":1,"deaths":0,"recovered":0},"dt":"3/17/20","ts":1584403200.0}"

**Comment by nat236919** [comment]
I believe API v2 solves the problem

https://covid2019-api.herokuapp.com/v2/country/cr

`{"data":{"location":"Costa Rica","confirmed":454,"deaths":2,"recovered":16,"active":436},"dt":"2020-04-05 23:13:44","ts":1586128424.0}`
