### ISSUE TITLE
Country code is  not consistent across all the APIs

### ISSUE THREAD

**Issue by RamanujamVaradhan** [nat236919/covid19-api#33]
For example : Country/Region value for south Korea in the timeseries API is
"Country/Region":"Korea,_South"

In the current API, the location is 
"location":"Korea, South" (without underscore and with a space)

Can we use consistent naming of countries across all the APIs?

**Comment by nat236919** [comment]
With API v2, most of the issues should be fixed. As for the name consistency, v2 will not change any given country names from the source data anymore (unlike API v1 where country names are modified).
