### ISSUE TITLE
Change NovelCoronaAPIv1 to CovidAPIv1 for consistency

### ISSUE THREAD

**Issue by nat236919** [nat236919/covid19-api#59]
I would like to change the name of APIv1's model from **NovelCoronaAPIv1** to **CovidAPIv1** to make it consistent with APIv2.

**Tasks**

1. Change the model's name from **NovelCoronaAPIv1** to **CovidAPIv1**
2. Make sure that all methods' names used by this model are fixed accordingly
3. Submit a PR to **development** branch

**Example:**

- Old

`novel_corona_api = NovelCoronaAPIv1() `

- New

`COVID_API_V1 = CovidAPIv1() # new - global scope`

**Comment by melsaa** [comment]
I'd like to work on this issue.
