### ISSUE TITLE
Testing with pytest needs to be updated folder changes with integrators. 

### ISSUE THREAD

**Issue by owen-duncan-snobel** [nat236919/covid19-api#71]
**Describe the bug**
When the project was refactored (integrators implemented) the tests used in the test folder with pytest broke since the file paths are different. V2 and V1 both break.

**To Reproduce**
1. Clone project run
2. run pytest 
3. See errors 

**Expected behavior**
 After running pytest you will see errors from incorrect imports of the models and utils folder and integrator instance name is different from the older version.
**Screenshots**
![image](https://user-images.githubusercontent.com/43126781/111019035-aa405380-838a-11eb-9b41-3721ff0346f9.png)

**Additional context**
I will update the file paths and make a PR, but their will need to be added testing implemented for each method if you are wishing to verify the correct model used for each method in the integrator file.

**Comment by owen-duncan-snobel** [comment]
This update / PR is related, testing will still need to be added to integrators if you wish to use / implement with TravisCI
https://github.com/nat236919/covid19-api/pull/70/commits/b22539b080d491d806fd4044a69c73d4e249b4ae

**Comment by nat236919** [comment]
@owen-duncan-snobel Currently tests are only implemented with **test_get_data.py** and **test_helper.py**

I have been having a problem with **test_covid_integrator_api_v1.py** and **test_covid_integrator_api_v2.py** as you have noticed. Unfortunately, no solution on my part so far.

Ref: https://github.com/nat236919/covid19-api/tree/development/app/tests
